### ISSUE TITLE
Doesn't render mapscii correctly

### ISSUE THREAD

**Issue by nonetrix** [vmttmv/stvk#1] opened 2022-01-15 09:49 UTC
![2022-01-15-034830_1920x1080_scrot](https://user-images.githubusercontent.com/45698918/149617494-402123b2-2dd5-46c9-829c-a99d00bcadb0.png)

Also amazing work seems about on par with Alacritty testing with https://github.com/alacritty/vtebench I want to see this project continue :D

**Comment by vmttmv** [comment] 2022-01-19 22:21
I haven't touched this project in a while, it was somewhat of a can-i-do-this-quickly -sort of thing.
The bug is due to the fork not implementing st's original font caching mechanism, which uses fontconfig to load and look up a glyph when it encounters one that is not present in the user-selected (and fontconfig matched) fonts.
The fix should be fairly straightforward, as the fontconfig-stuff can be lifted from the original st, and allocate more `Font` structures to hold the attributes and glyph LUTs. I may look into the issue next week.

**Comment by vmttmv** [comment] 2022-09-06 11:00
Fixed in https://github.com/vmttmv/stvk/commit/592694982608bebbd99e2f354419b7603c2bfb18

EDIT: Take that back. Above commit implements fallback fonts, however does not fix this particular issue.
However, I have been able to reproduce the same artefact across a variety of terminal emulators (xterm, kitty, alacritty), could this be a bug in mapscii itself?

**Closed as completed by vmttmv** 2022-09-06 11:00 UTC
